// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  $("#registrationForm").on("submit", function() {
    var email, mobileno, postData, size, usrname;
    usrname = $(".usrname").val();
    email = $(".email").val();
    mobileno = $(".mobileno").val();
    size = $(".peopleinhome").val();
    postData = {
      usrname: usrname,
      flatno: flatno,
      email: email,
      mobileno: mobileno,
      size: size
    };
    return $.ajax({
      type: "POST",
      url: "",
      data: postData,
      dataType: "json",
      success: function(returnData) {
        alert("success");
      }
    });
  });
  $('.submit').on("click", function() {
    window.location.hash = "#home";
    return setTimeout(function() {
      return $.ajax({
        type: "GET",
        url: "data/popup.json",
        dataType: "json",
        success: function(resp) {
          if (resp.popupflag === true) {
            $('.usagewarning').popup('open');
          }
        }
      });
    }, 1000);
  });
  $('.pledge').on("click", function() {
    $('.usagewarning').popup('close');
    setTimeout(function() {
      return $('.restorewater').popup('open');
    }, 1000);
    return setTimeout(function() {
      return $('.restorewater').popup('close');
    }, 5000);
  });
  return $('.leaveit').on("click", function() {
    debugger;
    $('.usagewarning').popup('close');
    return setTimeout(function() {
      return $('.icon-Pledge').show();
    }, 1000);
  });
});
