// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  $("#registrationForm").on("submit", function() {
    var email, mobileno, postData, size, usrname;
    usrname = $(".usrname").val();
    email = $(".email").val();
    mobileno = $(".mobileno").val();
    size = $(".peopleinhome").val();
    postData = {
      usrname: usrname,
      flatno: flatno,
      email: email,
      mobileno: mobileno,
      size: size
    };
    $.ajax({
      type: "POST",
      url: "",
      data: postData,
      dataType: "json",
      success: function(returnData) {
        alert("success");
      }
    });
  });
  return $('.pledge').on("click", function() {
    $('.consumtionoption').popup('close');
    return setTimeout(function() {
      return $('.restorewater').popup('open');
    }, 1000);
  });
});
